global:
  scrape_interval:     10s
  evaluation_interval: 30s
  external_labels:
    monitor: "dist-go"

scrape_configs:
  - job_name: rabbit
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbit:9090']

  - job_name: boiler-temp-runtime
    metrics_path: /runtime-metrics
    static_configs:
      - targets: ['boiler-temp:2112']

  - job_name: boiler-pressure-runtime
    metrics_path: /runtime-metrics
    static_configs:
      - targets: ['boiler-pressure:2112']

  - job_name: boiler-current-runtime
    metrics_path: /runtime-metrics
    static_configs:
      - targets: ['boiler-current:2112']

  - job_name: boiler-mixer-runtime
    metrics_path: /runtime-metrics
    static_configs:
      - targets: ['boiler-mixer:2112']

  - job_name: coordinator-runtime
    metrics_path: /runtime-metrics
    static_configs:
      - targets: ['coordinator:2112']
