global:
  scrape_interval:     10s
  evaluation_interval: 30s
  external_labels:
    monitor: "dist-go"

scrape_configs:
  - job_name: rabbit
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbit:9090']
